<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="6" passed="4" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-03-05T16:47:35 IST" name="Suite" finished-at="2025-03-05T16:49:02 IST" duration-ms="86694">
    <groups>
    </groups>
    <test started-at="2025-03-05T16:47:35 IST" name="Test" finished-at="2025-03-05T16:49:02 IST" duration-ms="86694">
      <class name="TestCases.LoginDataDrivenTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:TestCases.LoginDataDrivenTest@368f2016]" started-at="2025-03-05T16:47:35 IST" name="setup" finished-at="2025-03-05T16:47:43 IST" duration-ms="7961" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="DDTLoginTest(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:TestCases.LoginDataDrivenTest@368f2016]" started-at="2025-03-05T16:47:45 IST" name="DDTLoginTest" data-provider="provider" finished-at="2025-03-05T16:48:00 IST" duration-ms="15327" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[manikantasrinath123@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[aghadf@123]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Valid]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at TestCases.LoginDataDrivenTest.DDTLoginTest(LoginDataDrivenTest.java:30)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DDTLoginTest -->
        <test-method signature="DDTLoginTest(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:TestCases.LoginDataDrivenTest@368f2016]" started-at="2025-03-05T16:48:00 IST" name="DDTLoginTest" data-provider="provider" finished-at="2025-03-05T16:48:15 IST" duration-ms="15217" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[uday56@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[dbavsd@541]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Invalid]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DDTLoginTest -->
        <test-method signature="DDTLoginTest(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:TestCases.LoginDataDrivenTest@368f2016]" started-at="2025-03-05T16:48:15 IST" name="DDTLoginTest" data-provider="provider" finished-at="2025-03-05T16:48:31 IST" duration-ms="15896" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[hari420@gamil.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[gasvd@741]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Invalid]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DDTLoginTest -->
        <test-method signature="DDTLoginTest(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:TestCases.LoginDataDrivenTest@368f2016]" started-at="2025-03-05T16:48:31 IST" name="DDTLoginTest" data-provider="provider" finished-at="2025-03-05T16:48:38 IST" duration-ms="7248" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Admin]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[admin123]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Valid]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DDTLoginTest -->
        <test-method signature="DDTLoginTest(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:TestCases.LoginDataDrivenTest@368f2016]" started-at="2025-03-05T16:48:38 IST" name="DDTLoginTest" data-provider="provider" finished-at="2025-03-05T16:48:54 IST" duration-ms="15709" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[rohith77@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[hdsba@789]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Invalid]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DDTLoginTest -->
        <test-method signature="DDTLoginTest(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:TestCases.LoginDataDrivenTest@368f2016]" started-at="2025-03-05T16:48:54 IST" name="DDTLoginTest" data-provider="provider" finished-at="2025-03-05T16:49:02 IST" duration-ms="7730" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Admin]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[admin123]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Invalid]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at TestCases.LoginDataDrivenTest.DDTLoginTest(LoginDataDrivenTest.java:37)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DDTLoginTest -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:TestCases.LoginDataDrivenTest@368f2016]" started-at="2025-03-05T16:49:02 IST" name="teardown" finished-at="2025-03-05T16:49:02 IST" duration-ms="106" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- TestCases.LoginDataDrivenTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
